branches:
  only:
    - master

platform: Any CPU

configuration: Debug

before_build:
  - nuget restore
  - choco install opencover.portable
  - choco install codecov

after_build:
  - dotnet build
  - OpenCover.Console.exe -register:user -target:"%xunit20%\xunit.console.x86.exe" -targetargs:".\DemoTest\obj\Debug\netcoreapp3.1\DemoTest.dll -noshadow" -output:".\Myproject_coverage.xml"
  - codecov -f "MyProject_coverage.xml"