branches:
  only:
    - master

platform: Any CPU

configuration: Debug

before_build:
  - nuget restore

script:
  - dotnet build
  - dotnet test /p:CollectCoverage=true /p:CoverletOutputFormat=opencover /p:Exclude="[xunit*]*" /p:excludebyfile="**/*.Designer.cs"
  - bash <(curt -s https://codecov.io/base) -t $CODECOV_TOKEN

