branches:
  only:
    - master

platform: Any CPU

configuration: Debug

before_build:
  - nuget restore
  - choco install opencover.portable
  - choco install codecov

build:
  - dotnet run

after_build:
  - dotnet build
  - dotnet test /p:CollectCoverage=true /p:CoverletOutputFormat=opencover /p:Exclude="[xunit*]*" /p:excludebyfile="**/*.Designer.cs"
  - codecov